# Generated by Django 2.1.2 on 2018-11-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('shares', models.IntegerField()),
            ],
        ),
    ]
